url: https://librarycarpentry.github.io
baseurl: /new-website

# Site settings
title: Library Carpentry
email: team@carpentries.org
description: "Software and data skills for librarians"


# Team names, titles and social links
people:
- name: Jez Cope (UK)
  pic: jezcope
  social:
    - title: fab fa-twitter
      url: https://twitter.com/jezcope
    - title: fa fa-github
      url: https://github.com/jezcope

- name: Tim Dennis (USA)
  pic: timdennis
  social:
    - title: fab fa-twitter
      url: https://twitter.com/jt14den
    - title: fab fa-github
      url: https://github.com/jt14den  

- name: Chris Erdmann (USA)
  pic: chriserdmann
  social:
    - title: fab fa-twitter
      url: https://twitter.com/libcce
    - title: fab fa-github
      url: https://github.com/libcce
      
- name: Kayleigh Lino (South Africa)
  social:
    - title: fab fa-twitter
      url: https://twitter.com/CuratorKay
      
- name: Cam Macdonell (Canada)
  pic: cammacdonell
  social:
    - title: fab fa-twitter
      url: https://twitter.com/cjmacdonell
    - title: fab fa-github 
      url: https://github.com/cmacdonell 
  
- name: Juliane Schneider (USA)
  social:
    - title: fab fa-twitter
      url: https://twitter.com/JulianeS
    - title: fab fa-github
      url: https://github.com/pitviper6 
      
- name: Richard Vankoningsveld (Australia)
  social:
    - title: fab fa-twitter
      url: https://twitter.com/richyvk
    - title: fab fa-github
      url: https://github.com/richyvk 
 
- name: Belinda Weaver (Convenor - Australia)
  pic: belindaweaver
  social:
    - title: fab fa-twitter
      url: https://twitter.com/cloudaus
    - title: fab fa-github
      url: https://github.com/weaverbel
      
- name: Greg Wilson (Canada) (Advisory Role)
  social:
    - title: fab fa-twitter
      url: https://twitter.com/gvwilson  
    - title: fab fa-github
      url: https://github.com/gvwilson 
                  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fab fa-twitter
    url: http://twitter.com/libcarpentry
  - title: fab fa-github
    url: https://github.com/LibraryCarpentry/
  - title: fab fa-gitter   
    url: https://gitter.im/LibraryCarpentry/Lobby

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
