url: https://librarycarpentry.github.io
baseurl: /new-website

# Site settings
title: Library Carpentry
email: team@carpentries.org
description: "Software and data skills for librarians"


# Team names, titles and social links
people:
- name: Belinda Weaver (Australia)
  position: Community and Communications Lead, The Carpentries
  social:
    - title: fab fa-twitter
      url: https://twitter.com/cloudaus
    - title: fab fa-github
      url: https://github.com/weaverbel
    - title: fa fa-envelope
      url: mailto:bweaver@carpentries.org

- name: Chris Erdmann (USA)
  position: Library Carpentry Community and Development Director
  social:
    - title: fab fa-twitter
      url: https://twitter.com/libcce
    - title: fab fa-github
      url: https://github.com/libcce
    - title: fa fa-envelope
      url: mailto:chris@carpentries.org

- name: Jez Cope (UK)
  position: University of Sheffield Library
  social:
    - title: fab fa-twitter
      url: https://twitter.com/jezcope
    - title: fa fa-github
      url: https://github.com/jezcope

- name: Cam Macdonell (Canada)
  position: McEwan University
  social:
    - title: fab fa-twitter
      url: https://github.com/cmacdonell

- name: Tim Dennis (USA)
  position: UCLA Library
  social:
    - title: fab fa-twitter
      url: https://twitter.com/jt14den
    - title: fab fa-github
      url: https://github.com/jt14den  

- name: Juliane Schneider (USA)
  position: UCLA Library
  social:
    - title: fab fa-twitter
      url: https://twitter.com/JulianeS
    - title: fab fa-github
      url: https://github.com/pitviper6 
          
- name: Kayleigh Lino (South Africa)
  position: TBA
  social:
    - title: fab fa-twitter
      url: https://twitter.com/CuratorKay
      
- name: Richard Vankoningsveld (Australia)
  position: Supreme Court Library
  social:
    - title: fab fa-twitter
      url: https://twitter.com/richyvk
    - title: fab fa-github
      url: https://github.com/richyvk 
      
- name: Greg Wilson (Canada) (Advisory Role)
  position: DataCamp
  social:
    - title: fab fa-twitter
      url: https://twitter.com/gvwilson  
    - title: fab fa-github
      url: https://github.com/gvwilson 
                  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: fab fa-twitter
    url: http://twitter.com/libcarpentry
  - title: fab fa-github
    url: https://github.com/LibraryCarpentry/
  - title: fab fa-gitter   
    url: https://gitter.im/LibraryCarpentry/Lobby

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
