url: https://librarycarpentry.github.io
baseurl: /new-website

# Site settings
title: Library Carpentry
email: team@carpentries.org
description: "Software and data skills for librarians"


# Team names, titles and social links
people:
- name: Belinda Weaver
  pic: 
  position: Community and Communications Lead, The Carpentries
  social:
    - title: twitter
      url: https://twitter.com/cloudaus
    - title: github
      url: https://github.com/weaverbel
    - title: linkedin
      url: https://www.linkedin.com/in/belinda-weaver-8525526/

- name: Chris Erdmann 
  pic: 
  position: Community Development Lead
  social:
    - title: twitter
      url: https://twitter.com/libcce


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/libcarpentry
  - title: github
    url: https://github.com/LibraryCarpentry/
  - title: gitter   
    url: https://gitter.im/LibraryCarpentry/Lobby

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
